name: Igor D.C.
description: Build the Thrill

url: https://igordc.com

baseurl: ''

github: 'igordcard'
gitlab: 'igordc'
twitter: 'igordcard'
medium: 'igordc'
linkedin: 'igordcard'

gaaccount: 'UA-12412635-4'

disqus: 'igordcard'
comments: true

isso: ''

permalink: /:year/:month/:title
paginate: 6

highlighter: rouge

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

markdown: kramdown

gems: ['jekyll-sitemap', 'jekyll-paginate']

exclude: ['README.md', 'LICENSE']
